# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0002_auto_20190114_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Portal',
                'verbose_name_plural': 'Portal',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('task_count_open', models.IntegerField(default=0)),
                ('milestone_count_open', models.IntegerField(default=0)),
                ('task_count_close', models.IntegerField(default=0)),
                ('milestone_count_close', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date_format', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date_format', models.DateTimeField(blank=True, max_length=1000, null=True)),
                ('folder_url', models.URLField(blank=True, null=True)),
                ('milestone_url', models.URLField(blank=True, null=True)),
                ('forum_url', models.URLField(blank=True, null=True)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('status_url', models.URLField(blank=True, null=True)),
                ('event_url', models.URLField(blank=True, null=True)),
                ('task_url', models.URLField(blank=True, null=True)),
                ('bug_url', models.URLField(blank=True, null=True)),
                ('self_url', models.URLField(blank=True, null=True)),
                ('timesheet_url', models.URLField(blank=True, null=True)),
                ('user_url', models.URLField(blank=True, null=True)),
                ('tasklist_url', models.URLField(blank=True, null=True)),
                ('activity_url', models.URLField(blank=True, null=True)),
                ('end_date_format', models.CharField(blank=True, max_length=100, null=True)),
                ('id_bug_enabled', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Projects',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='tokens',
            options={'ordering': ('-created_at',), 'verbose_name': 'Tokens', 'verbose_name_plural': 'Tokens'},
        ),
    ]
