# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0003_auto_20190115_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
