# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0004_auto_20190115_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='start_date_format',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
