# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0005_auto_20190115_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_id', models.CharField(max_length=100, unique=True)),
                ('self_url', models.URLField(blank=True, null=True)),
                ('timesheet_url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('task_id', models.CharField(max_length=1000, unique=True)),
                ('task_key', models.CharField(max_length=1000, unique=True)),
                ('created_person', models.CharField(max_length=1000, unique=True)),
                ('created_time', models.CharField(blank=True, max_length=100, null=True)),
                ('subtasks', models.CharField(blank=True, max_length=100, null=True)),
                ('work', models.CharField(blank=True, max_length=100, null=True)),
                ('completed', models.CharField(blank=True, max_length=1000, null=True)),
                ('percent_complete', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_updated_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('completed_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('task_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('tasklist_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(blank=True, max_length=1000, null=True)),
                ('color_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('end_date', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohobasic.Projects')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='ZohoUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohobasic.Tasks')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Zoho Users',
                'verbose_name_plural': 'Zoho Users',
            },
        ),
    ]
