# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0006_tasks_zohousers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_person',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='milestone_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_key',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
