# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0007_auto_20190115_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='start_date',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
