# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0009_auto_20190115_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
