# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0011_auto_20190115_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified_date', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_status', models.CharField(blank=True, max_length=100, null=True)),
                ('time_sheet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hours', models.CharField(blank=True, max_length=100, null=True)),
                ('total_minutes', models.CharField(blank=True, max_length=100, null=True)),
                ('hours_display', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohobasic.Projects')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohobasic.Tasks')),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Time Sheet',
                'verbose_name_plural': 'Time Sheet',
            },
        ),
    ]
