# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-16 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0013_milestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ('-created_at',), 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestone'},
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='task',
        ),
    ]
