# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohobasic', '0014_auto_20190116_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
