# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-02 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userzoho', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='access_token',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='code',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='refresh_token',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
