# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-04 05:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userzoho', '0002_auto_20190202_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_task_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('depth', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, max_length=1000, null=True)),
                ('percent_complete', models.CharField(blank=True, max_length=1000, null=True)),
                ('duration', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completed', models.CharField(max_length=1000, unique=True)),
                ('created_person', models.CharField(max_length=1000, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_fk', to='userzoho.Tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Tasks',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
