# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-04 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userzoho', '0004_auto_20190204_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtasks',
            name='completed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
