# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-04 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userzoho', '0005_auto_20190204_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_list_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('completed', models.CharField(blank=True, max_length=1000, null=True)),
                ('milestone_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('rolled', models.CharField(blank=True, max_length=1000, null=True)),
                ('sequence', models.CharField(blank=True, max_length=1000, null=True)),
                ('view_type', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userzoho.Projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'verbose_name': 'Sub Tasks',
                'verbose_name_plural': 'Sub Tasks',
            },
        ),
    ]
